# Generated by Django 4.2.13 on 2024-06-08 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_about_alter_comment_options_alter_post_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='About',
        ),
    ]
